package canopy.engine.data.registry

/**
 * Generic entry with a domain and entry name - id is generated by appending both
 * @see IdRegistry
 */
interface IdEntry {
    val domain: String
    val name: String
    val id: String get() = "$domain:$name"
}
